{{- $splitValue := split "-" .Capabilities.KubeVersion.Version -}}  
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  apiVersions.txt: |
    {{ .Capabilities.APIVersions }}
  KubeVersion.txt: |
    {{ .Capabilities.KubeVersion }}
    {{ .Capabilities.KubeVersion.Version }}
    {{ split "-" "v1.24.17-eks-8cb36c9" }}
    {{ index $splitValue "_0" }}
