apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  apiVersions.txt: |
    {{ .Capabilities.APIVersions }}
  KubeVersion.txt: |
    {{ .Capabilities.KubeVersion }}
    {{ .Capabilities.KubeVersion.Version }}
